### ISSUE TITLE
npm start后在浏览器中访问有报错

### ISSUE THREAD

**Issue by jackie19** [angular-bbs/user-ui#11]
1　下载最新的代码并npm install 安装依赖

2　npm start ，控制台一切正常

3　浏览器访问http://localhost:4200/ 报错：　
`core.umd.js:3462 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'annotations' of undefined`

node 版本 5.12.0
npm 版本 3.8.6 

![7ca2 tmp](https://cloud.githubusercontent.com/assets/2063608/19232430/506d46f4-8f12-11e6-8af4-49469c324c01.jpg)

**Comment by rexebin** [comment]
请暂时使用Team分支。该分支采用了不同的环境，并升级到了Angular 2.1
