### ISSUE TITLE
API 遗漏

### ISSUE THREAD

**Issue by trotyl** [angular-bbs/user-ui#7]
> - `path`是一个用作路由匹配规则DSL的字符串。
> - `pathMatch`是一个用来指定匹配策略的字符串，比如完全匹配还是部分匹配。
> - `component`是要渲染出的组件类。
> - `redirectTo`是一个重定向指令，用来指定跳转到的地址。
> - `outlet`用在多视图路由中，它用来指定当前路由组件要渲染到的位置。
> - `canActivate`是一个数组，Angular会在激活某个路由前，先调用该数组中的这些服务，任何一个返回否，就会禁止进入该路由。
> - `canActivateChild`跟`canActivate`类似，但是作用于当前路由的各级子路由。
> - `canDeactivate`跟`canActivate`相反，`canActivate`是用来判断是否可以进入该路由的，而`canDeactivate`是判断是否可以从当前路由离开，比如当用户修改了却还没有保存时，就可以通过它阻止离开。
> - `data`是为组件提供的附加数据，组件中可以通过`ActivatedRoute`服务来取得它。
> - `resolve`和Angular 1中路由的resolve机制类似，也是用于为组件提供动态服务的。
> - `children`是当前路由的子路由的数组。
> - `loadChildren`则用来支持延迟加载（LazyLoad）子模块。

这里漏了一个 `canLoad` 。。

**Comment by trotyl** [comment]
@asnowwolf

**Comment by CrazyBBer** [comment]
以‘/’ 开头和 pathMatch:full 的路径字符串就表示完全匹配？

**Comment by asnowwolf** [comment]
好，回头加上，我直接从API文档拷贝的，没注意文档没列全。

**Comment by asnowwolf** [comment]
不是，是否完全只取决于pathMatch

2016年9月28日 上午9:24，"Eamon" notifications@github.com写道：
